name: Node.js Package
on:
  push:
  release:
    types: [created]

jobs:
  publish-es-lint-config:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: "https://npm.pkg.github.com"
          scope: "@kwizapp"
      - run: npm publish eslint-config
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish-prettier-config:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: "https://npm.pkg.github.com"
          scope: "@kwizapp"
      - run: npm publish prettier-config
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
